/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WtfLogo {}
  interface WtfLogoAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'WtfLogo': Components.WtfLogo;
  }

  interface StencilIntrinsicElements {
    'wtf-logo': Components.WtfLogoAttributes;
  }


  interface HTMLWtfLogoElement extends Components.WtfLogo, HTMLStencilElement {}
  var HTMLWtfLogoElement: {
    prototype: HTMLWtfLogoElement;
    new (): HTMLWtfLogoElement;
  };

  interface HTMLElementTagNameMap {
    'wtf-logo': HTMLWtfLogoElement
  }

  interface ElementTagNameMap {
    'wtf-logo': HTMLWtfLogoElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
